name: DNSForwarder
main: com.github.suprememortal.dnsforwarder.DNSForwarder
version: "IGN"
api: ["1.0.0"]
author: SupremeMortal
description: Forward players to a specific server from a mapped DNS address.
website: https://github.com/SupremeMortal/DNSForwarder